### ISSUE TITLE
How to manually trigger a session save

### ISSUE THREAD

**Issue by the-lazy-fox** [linuxserver/docker-rutorrent#121] opened 2019-06-04 11:21 UTC
Hi there,

I'm running the last version of the container and I figured out that a `docker stop` doesn't save the rtorrent session before stopping the container itself.

Is it possible to add this feature?
Otherwise, can I call `session.save` myself somehow?

Thanks for your help,

Regards

**Comment by piramiday** [comment] 2020-07-08 16:13
I think you should be able to issue a session save by yourself by pressing `CTRL-X` and then typing `session.save=` 

you can add a schedule to your rtorrent RC file to automatically save session data every so often.
depending on how many torrents you have that might be straining your disk, though.

take a look here: https://github.com/rakshasa/rtorrent/wiki/Performance-Tuning#session-save

for the record, I agree that this rtorrent configuration file should be **heavily** updated! e.g. #148 and #157 ...

**Comment by the-lazy-fox** [comment] 2020-07-11 14:14
Hi,
Thanks for the tips. I will try if I can run this with a Docker exec command, don’t know if it’s possible.

Btw this performance tuning file caused me more trouble than ever! I reverted it!

**Comment by piramiday** [comment] 2020-07-11 15:29
> by pressing `CTRL-X` and then typing `session.save=`

this would have to be done inside rtorrent, therefore you would need to attach to rtorrent's `screen` session in your container.
with default naming, something like this should be executed on the host:
```
docker exec -it rutorrent screen -r
```

but **if you have no idea how to interact with the terminal interface of `rtorrent`, I highly discourage it**.

.

> Btw this performance tuning file caused me more trouble than ever! I reverted it!

for example, this line instructs `rtorrent` to save the session data every 10 minutes:
```
schedule2 = session_save, 600, 600, ((session.save))
```
you can add this to your rtorrent `.rc` file:
- `/config/rutorrent/rtorrent/rtorrent.rc` while in the container, or
- `/path/to/rutorrent/docker/config/rutorrent/rtorrent/rtorrent.rc` on the host.

if you have further problems it might mean that you are doing something wrong -- then it would probably be better if you asked for help on https://github.com/rakshasa/rtorrent/issues.

remember to close this issue if you manage to solve your problem!

**Comment by the-lazy-fox** [comment] 2020-07-21 05:54
Thanks @piramiday !
I would like to have one line from the host to trigger it, because it’s seems that the Linuxserver container doesn’t save the session before a shutdown or a restart. I have already the automatic saving but less less frequent due to the volume of torrents.
I will give a try as soon as possible

**Comment by mabushey** [comment] 2021-02-16 19:07
The problem is key presses in the rtorrent screen GUI take about 2 and a half minutes to register (i7/32GB RAM). Is screen causing some kind of loop? Also screen -r may not work right, you may also have to add -f as to not block some ctrl chars: `docker exec -it rutorrent sh -c "screen -f -r"`

**Closed as completed** 2022-02-23 22:41 UTC
Labels: enhancement, no-issue-activity
