### ISSUE TITLE
issue with XMLRPC

### ISSUE THREAD

**Issue by saitoh183** [linuxserver/docker-rutorrent#76] opened 2018-02-19 01:18 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

When i start the container, not long after, i get 

```
 Bad response from server: (500 [error,list]) Link to XMLRPC failed. May be, rTorrent is down?
```
And it keep repeating every 5 minutes.

It is running on my online.net SC box

CPU
1x Intel® C2350 (Avoton)

RAM
4 GB DDR3 ECC

Storage
1x 1 TB SATA 

Logs are also weird:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

```
RCtorrent.rc
```
execute = {sh,-c,/usr/bin/php7 /usr/share/webapps/rutorrent/php/initplugins.php abc &}
execute.nothrow = rm,/run/php/.rtorrent.sock
network.scgi.open_local = /run/php/.rtorrent.sock
schedule = socket_chmod,0,0,"execute=chmod,0660,/run/php/.rtorrent.sock"
schedule = socket_chgrp,0,0,"execute=chgrp,abc,/run/php/.rtorrent.sock"
#log.open_file = "rtorrent", /config/log/rtorrent/rtorrent.log
# ------ BEGIN LOG FILE CREATION ------
log.open_file = "rtorrent", /config/log/rtorrent/rtorrent.log
log.open_file = "tracker", /config/log/rtorrent/tracker.log
log.open_file = "storage", /config/log/rtorrent/storage.log

log.add_output = "info", "rtorrent"
log.add_output = "critical", "rtorrent"
log.add_output = "error", "rtorrent"
log.add_output = "warn", "rtorrent"
log.add_output = "notice", "rtorrent"
log.add_output = "debug", "rtorrent"

log.add_output = "dht_debug", "tracker"
log.add_output = "tracker_debug", "tracker"

log.add_output = "storage_debug", "storage"
# ------ END LOG FILE CREATION ------
#log.add_output = "info", "rtorrent"
min_peers = 40
max_peers = 1200
max_uploads = 15
download_rate = 0
upload_rate = 0
# schedule = watch_directory_1,5,5,"load.start=/downloads/watched/*.torrent"
directory = /downloads/incoming
session = /config/rtorrent/rtorrent_sess
schedule = low_diskspace,5,60,close_low_diskspace=100M
# ip = 178.32.28.51
bind = 0.0.0.0
port_range = 51413-51413
check_hash = yes
use_udp_trackers = yes
encryption = allow_incoming,try_outgoing,enable_retry
dht = auto
dht_port = 6881
peer_exchange = yes
# network.http.ssl_verify_peer.set=0
# scgi_port = 0.0.0.0:5000
encoding_list = UTF-8
# system.umask.set = 022
schedule2 = session_save, 1200, 10800, ((session.save))
# Maximum number of simultaneous downloads and uploads slots (global slots!) (`max_downloads_global`, `max_uploads_global`)
throttle.max_downloads.global.set = 300
throttle.max_uploads.global.set   = 300
# Set the max amount of memory address space used to mapping file chunks. This refers to memory mapping, not
#  physical memory allocation. Default: `1GB` (`max_memory_usage`) 
# This may also be set using ulimit -m where 3/4 will be allocated to file chunks.
#pieces.memory.max.set = 3072M
```
I have tried some stuff i found online but nothing seems to work. what causes this and what can i do to fix it?

Also i get 

```
The request to rTorrent has timed out.
```

**Comment by saitoh183** [comment] 2018-02-21 13:08
So i changed machines and im still getting this same error
```
Bad response from server: (500 [error,list]) Link to XMLRPC failed. May be, rTorrent is down?
```

**Comment by racincason** [comment] 2018-03-03 20:00
Having the exact same issue. 

Crashes anywhere from 10 min to 1 hour. After that it's re-checking all the files being processed and then starts over again. I've upped the ram in the php from 128 to 1024. I only have about 100 files right now. 
I see there are 2 issues open about this with no responses. 

Any help would be greatly appreciated. 


`[03.03.2018 12:03:32] WebUI started.
[03.03.2018 12:13:45] Bad response from server: (0 [error,list])
[03.03.2018 12:18:46] Bad response from server: (500 [error,list]) Link to XMLRPC failed. May be, rTorrent is down?
[03.03.2018 12:24:17] Bad response from server: (500 [error,list]) Link to XMLRPC failed. May be, rTorrent is down?
[03.03.2018 12:57:05] Bad response from server: (500 [error,list]) Link to XMLRPC failed. May be, rTorrent is down?
[03.03.2018 13:30:25] Bad response from server: (500 [error,gettotal]) Link to XMLRPC failed. May be, rTorrent is down?`

`<value><string>d.custom.set=x-filename,</string></value>^M
<value><string>d.directory.set="/downloads/completed"</string></value>^M
</data></array></value></member></struct></value>^M
</data></array></value></param></params></methodCall>
[01.03.18 19:22:56] Status: 200 OK^M
Content-Type: text/xml^M
Content-Length: 372^M
^M
<?xml version="1.0" encoding="UTF-8"?>^M
<methodResponse>^M
<fault>^M
<value><struct>^M
<member><name>faultCode</name>^M
<value><i4>-503</i4></value></member>^M
<member><name>faultString</name>^M
<value><string>Call XML not a proper XML-RPC call.  XML-RPC request too large.  Max allowed is 524288 bytes</string></value></member>^M
</struct></value>^M
</fault>^M
</methodResponse>^M
 
[02.03.18 00:41:52] <?xml version="1.0" encoding="UTF-8"?><methodCall><methodName>throttle.global_down.max_rate.set</methodName><params>^M
<param><value><string></string></value></param>^M
<param><value><i8>1023998976</i8></value></param>^M
</params></methodCall>
[02.03.18 00:41:52] Status: 200 OK^M
Content-Type: text/xml^M
Content-Length: 320^M
^M
<?xml version="1.0" encoding="UTF-8"?>^M
<methodResponse>^M
<fault>^M
<value><struct>^M
<member><name>faultCode</name>^M
<value><i4>-503</i4></value></member>^M
<member><name>faultString</name>^M
<value><string>Max unchoked must be between 0 and 2^16.</string></value></member>^M
</struct></value>^M
</fault>^M
</methodResponse>^M`
# Here is my rctorrent.rc


`execute = {sh,-c,/usr/bin/php7 /usr/share/webapps/rutorrent/php/initplugins.php abc &}
execute.nothrow = rm,/run/php/.rtorrent.sock
network.scgi.open_local = /run/php/.rtorrent.sock
schedule = socket_chmod,0,0,"execute=chmod,0660,/run/php/.rtorrent.sock"
schedule = socket_chgrp,0,0,"execute=chgrp,abc,/run/php/.rtorrent.sock"
log.open_file = "rtorrent", /config/log/rtorrent/rtorrent.log
log.add_output = "info", "rtorrent"
min_peers = 1
max_peers = 12000
max_uploads = 500
download_rate = 50000
upload_rate = 50000
#directory = /downloads/incoming
directory = /downloads/completed
session = /config/rtorrent/rtorrent_sess
schedule = low_diskspace,5,60,close_low_diskspace=100M
#ip = Removed
bind = 0.0.0.0
port_range = 50815-50825
check_hash = yes
use_udp_trackers = yes
encryption = allow_incoming,try_outgoing,enable_retry
dht = auto
dht_port = 6881
peer_exchange = yes
#network.http.ssl_verify_peer.set=0
#scgi_port = 0.0.0.0:5000
encoding_list = UTF-8
#system.umask.set = 022

#Move completed torrents to different directory depending on watch directory
schedule2 = watch_directory_1,5,5,"load.start=/downloads/watched/*.torrent,d.custom3.set=/downloads/completed/"
method.insert = d.get_data_full_path, simple, "branch=((d.is_multi_file)),((cat,(d.directory))),((cat,(d.directory),/,(d.name)))"
method.insert = d.move_to_complete, simple, "d.directory.set=$argument.1=; execute=mkdir,-p,$argument.1=; execute=mv,-u,$argument.0=,$argument.1=; d.save_full_session="
method.set_key = event.download.finished,move_complete,"d.move_to_complete=$d.get_data_full_path=,$d.custom3="

#Move .torrent file after loading it manually
method.set_key = event.download.inserted_new,move_tor,"execute=mv,-u,$d.loaded_file=,/downloads/torrents/"`

**Comment by sparklyballs** [comment] 2018-03-03 20:05
noone in the team has been unable to reproduce the problem

we're basically stumped tbh

**Comment by D0rd** [comment] 2018-03-31 00:29
I'm having the same problem :(

**Comment by szukalski** [comment] 2018-05-09 08:59
Same pattern here also

**Comment by j0nnymoe** [comment] 2018-05-09 09:04
As stated by @sparklyballs earlier in the thread, we are unable to re-produce this issue in our test environments. Rather than just saying "same problem" - please provide relevant information we can work with: Host OS / Docker Version / docker command or docker-compose info / anything else you think would be relevant.

**Comment by szukalski** [comment] 2018-05-09 11:50
My apologies, I was as useful as tits on a bull.

My config file is below:
```execute = {sh,-c,/usr/bin/php7 /usr/share/webapps/rutorrent/php/initplugins.php abc &}
execute.nothrow = rm,/run/php/.rtorrent.sock
network.scgi.open_local = /run/php/.rtorrent.sock
schedule = socket_chmod,0,0,"execute=chmod,0660,/run/php/.rtorrent.sock"
schedule = socket_chgrp,0,0,"execute=chgrp,abc,/run/php/.rtorrent.sock"
log.open_file = "rtorrent", /config/log/rtorrent/rtorrent.log
log.add_output = "info", "rtorrent"

throttle.min_peers.seed.set = 30
throttle.max_peers.seed.set = 80
throttle.max_uploads.set = 100
throttle.max_uploads.global.set = 250

network.http.max_open.set = 50
network.max_open_files.set = 600
network.max_open_sockets.set = 300

pieces.memory.max.set = 1800M
network.xmlrpc.size_limit.set = 4M

pieces.hash.on_completion.set = no

download_rate = 10000
upload_rate = 10000
schedule = watch_directory_2,5,5,"load_start=/downloads/dropbox/watch/*.torrent"
schedule = watch_directory_3,5,5,"load_start=/downloads/dropbox/watch/*.txt"
directory = /downloads/incoming
session = /config/rtorrent/rtorrent_sess
schedule = low_diskspace,5,60,close_low_diskspace=100M
ip = Hahayeahright
bind = 0.0.0.0
port_range = 51413-51413
use_udp_trackers = yes
encryption = allow_incoming,try_outgoing,enable_retry
dht = auto
dht_port = 6881
peer_exchange = yes
encoding_list = UTF-8
```

I found that the crash seemed to happen around the time that rtorrent would have saved the session state (or when I saved a torrent in a new directory using Save to.. in rutorrent, maybe that enforces a state save?), so I enabled tracker logs and found errors on a torrent stating that the passkey was invalid. Once I removed that torrent then things have been ok.

**Comment by j0nnymoe** [comment] 2018-05-09 11:53
@szukalski could you provide the command you use to run the container aswell please? Wondering if it's something to do with that.

**Comment by szukalski** [comment] 2018-05-09 11:58
Sure thing @j0nnymoe 

It is part of a docker-compose [here](https://github.com/szukalski/docker-rutorrent/blob/master/docker-compose.yml) as part of a larger installation [here](https://github.com/szukalski/docker-rutorrent).

**Comment by szukalski** [comment] 2018-05-09 15:03
The issue has cropped up again though with decreased frequency. Will keep it relatively static to troubleshoot if there is anything you would like in order to assist.

**Comment by ravenich** [comment] 2018-08-07 10:39
Same errors on the latest version.

**Comment by szukalski** [comment] 2018-08-08 09:49
I have found two potential problems:
1 - DHT. Disable DHT and most problems resolve. This could be due to a specific torrent, but I didn't dig deeper.
2 - Corrupt torrent file.

You can check by changing the appropriate log level of your rtorrent in rtorrent.rc:

`log.open_file = "rtorrent", /config/log/rtorrent/rtorrent.log`
`log.add_output = "info", "rtorrent"`

Change to debug and do some troubleshooting. Always fun times.

**Comment by ravenich** [comment] 2018-08-09 06:45
Disabling DHT resolve the situation

**Comment by homerr** [comment] 2019-01-08 10:39
Going to close this as the issue was pre-pipeline building and before the container was re-written. If the issue has stuck around, let us know.

**Closed as completed by homerr** 2019-01-08 10:39 UTC
