### ISSUE TITLE
Lockfile not deleted on `docker stop`

### ISSUE THREAD

**Issue by deed02392** [linuxserver/docker-rutorrent#57] opened 2017-08-19 11:39 UTC
When running `docker stop` on this container, the rtorrent lock file is not deleted. This means that on subsequent starts of the container, rtorrent fails to execute (because the lock file still exists). I have to manually remove it between restarts.

Is this a known issue? Can it be addressed by sending some custom signal (`docker kill --signal=something`)?

**Comment by sparklyballs** [comment] 2017-08-19 11:43
there is a routine to delete existing lockfile on startup

https://github.com/linuxserver/docker-rutorrent/blob/master/root/etc/cont-init.d/20-config#L44

so if you have moved the lockfile in another config then this routine will no longer function

**Comment by deed02392** [comment] 2017-08-19 11:51
Thanks for the quick reply.

I can confirm this in my environment. However, this fails when the config is backed by an NFS share, because root perms are squashed here. Perhaps the right thing to do is have this script use the permissions provided by the envar for performing the rm operation?

**Comment by sparklyballs** [comment] 2017-08-19 11:53
so the issue is incorrect permissions on nfs share

closing

**Closed as completed by sparklyballs** 2017-08-19 11:53 UTC

**Comment by deed02392** [comment] 2017-08-19 11:54
@sparklyballs no it isn't. The perms are correct. But your script tries to run as root, and root has no universal privileges on NFS shares. So unless you do not want to support NFS mounts for /config, this is still an issue.

**Comment by deed02392** [comment] 2017-08-19 11:57
Additionally, the fact this lock file is left behind indicates rtorrent isn't gracefully shutting down. Shouldn't you be using a cont-finish.d script to send the appropriate signal to the rtorrent pid?

**Comment by sparklyballs** [comment] 2017-08-19 11:59
we do not recommend using remote shares for /config full stop

**Comment by deed02392** [comment] 2017-08-19 12:02
OK. Still, the presence of the lock file after docker stop is another issue that I'll raise separately.
